/**
 * volumes.json — the sealed MANIFEST of a volumes root (WP-U199 · D-45).
 *
 * Contract (manifest side):
 * - The manifest declares IDENTITY + TOPOLOGY only: `root`, `policy`,
 *   `note`, `volumes{disk, path, pathOverride, readonly, deferred, label,
 *   source, corpora[{id, path, label}]}`.
 * - It is READ-ONLY for the runtime. Its identity is the sha256 of its
 *   exact bytes on disk (the seal). Measuring NEVER modifies it; only an
 *   import may (re)write it, sealing a new hash. Since WP-U201 that single
 *   legitimate writer is `sealManifest()` below, used EXCLUSIVELY by the
 *   import pipeline (src/import.mjs · plan/CONTRATO-IMPORT-PACK-v1.md).
 * - Measured counters (`files`, `bytes`, `missing`, `measuredAt`) do NOT
 *   live here — they live in volumes.state.json (see state.mjs), which
 *   never enters the manifest hash.
 * - A volumes root WITHOUT a manifest is not operable: every operation
 *   aborts (throw), nothing is invented or scaffolded in its place.
 *
 * Rule (mesa D-45): if it can be regenerated by measuring, it is state,
 * not manifest.
 * Node-only.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { resolveVolumesRoot, resetVolumesCache } from '@zeus/presets-sdk/volumes';

export const MANIFEST_FILE_NAME = 'volumes.json';

/**
 * Absolute path of the manifest under the resolved volumes root.
 * @returns {string}
 */
export function resolveManifestPath() {
  return join(resolveVolumesRoot(), MANIFEST_FILE_NAME);
}

/**
 * Exact manifest bytes. Absent manifest = abort (never invent one).
 * @returns {{ path: string, raw: Buffer }}
 */
export function readManifestRaw() {
  const path = resolveManifestPath();
  if (!existsSync(path)) {
    throw new Error(
      `volumes.json not found at ${path} — a volumes root without a manifest is not operable; aborting`
    );
  }
  return { path, raw: readFileSync(path) };
}

/**
 * The seal: sha256 (hex) over the exact manifest bytes.
 * volumes.state.json never enters this hash.
 * @returns {{ path: string, sha256: string }}
 */
export function hashManifest() {
  const { path, raw } = readManifestRaw();
  return { path, sha256: createHash('sha256').update(raw).digest('hex') };
}

/**
 * IMPORT-ONLY manifest write (WP-U201 · CONTRATO-IMPORT-PACK-v1 paso 5).
 * The ONE legitimate writer of volumes.json: rewrites the whole manifest
 * object and returns the NEW seal. Requires an existing manifest (a root
 * without one is not operable — nothing is invented). Never call this from
 * measurement/runtime paths: measuring writes volumes.state.json only.
 * @param {object} config — full manifest object to persist
 * @returns {{ path: string, sha256: string }} new seal
 */
export function sealManifest(config) {
  const { path } = readManifestRaw(); // aborts when the root has no manifest
  writeFileSync(path, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
  resetVolumesCache();
  return hashManifest();
}
