/**
 * volumes.state.json — the LIVE STATE of a volumes root (WP-U199 · D-45).
 *
 * Contract (state side — counterpart of manifest.mjs):
 * - The state holds everything REGENERABLE BY MEASURING: per-volume and
 *   per-corpus `files`, `bytes`, `missing`, plus `measuredAt` and the
 *   `manifest.sha256` the measurement was taken against.
 * - It is MUTABLE and regenerable; it is NOT version-controlled and it
 *   NEVER enters the manifest hash (the seal covers volumes.json bytes
 *   only).
 * - State is only recorded for volumes the manifest declares: no manifest
 *   entry → the operation aborts upstream, no state is invented.
 * - Nothing is reconciled by mtime (U225): the recorded CONTENT is the
 *   truth; `measuredAt` is informative metadata, never a merge key.
 *
 * Shape (v1):
 *   {
 *     "version": 1,
 *     "manifest": { "sha256": "<hex of volumes.json bytes>" },
 *     "volumes": {
 *       "<volumeId>": {
 *         "files": n, "bytes": n, "missing": bool,
 *         "measuredAt": "<ISO>",
 *         "corpora": [{ "id", "path", "label", "files", "bytes", "missing" }]
 *       }
 *     }
 *   }
 *
 * Rule (mesa D-45): if it can be regenerated by measuring, it is state,
 * not manifest.
 * Node-only.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { resolveVolumesRoot } from '@zeus/presets-sdk/volumes';

export const STATE_FILE_NAME = 'volumes.state.json';
export const STATE_VERSION = 1;

/**
 * Absolute path of the state file under the resolved volumes root.
 * @returns {string}
 */
export function resolveVolumesStatePath() {
  return join(resolveVolumesRoot(), STATE_FILE_NAME);
}

/**
 * Load the state, or an empty scaffold when none exists yet.
 * (An absent state file is normal — it is born on first measurement.)
 * @returns {{ version: number, manifest?: { sha256: string }, volumes: object }}
 */
export function loadVolumesState() {
  const path = resolveVolumesStatePath();
  if (!existsSync(path)) {
    return { version: STATE_VERSION, volumes: {} };
  }
  return JSON.parse(readFileSync(path, 'utf8'));
}

/**
 * Persist the state file (pretty JSON + trailing newline).
 * @param {object} state
 * @returns {string} written path
 */
export function writeVolumesState(state) {
  const path = resolveVolumesStatePath();
  writeFileSync(path, `${JSON.stringify(state, null, 2)}\n`, 'utf8');
  return path;
}

/**
 * Record a LIVE SYNC mark for a volume (WP-U204).
 *
 * `syncedAt` is the timestamp of the last live producer run (jetstream sync,
 * SSB export…). It is LIVE STATE, never manifest: a temporal field inside
 * volumes.json would break the seal's stability on every sync (the exact
 * defect demolished here — feed-kit `ensureFirehoseVolumeLayout` wrote
 * `source.syncedAt` straight into the manifest with `writeFileSync`).
 * The manifest only changes by import.
 *
 * Fail-closed like the rest: a volume the manifest does not declare aborts —
 * no entry is invented (`hashManifest()` already aborts on a root without a
 * manifest).
 *
 * @param {string} volumeId
 * @param {{ syncedAt?: string, source?: object }} [mark]
 * @returns {{ statePath: string, state: object, syncedAt: string }}
 */
export function recordVolumeSync(volumeId, mark = {}) {
  const state = loadVolumesState();
  state.version = STATE_VERSION;
  state.volumes = state.volumes || {};
  const syncedAt = mark.syncedAt ?? new Date().toISOString();
  state.volumes[volumeId] = {
    ...(state.volumes[volumeId] || {}),
    syncedAt,
    ...(mark.source ? { source: mark.source } : {})
  };
  const statePath = writeVolumesState(state);
  return { statePath, state, syncedAt };
}

/**
 * Record one volume's live measurement into the state.
 * @param {string} volumeId
 * @param {{ files: number, bytes: number, missing?: boolean, corpora?: object[] }} measured
 * @param {{ manifestSha256?: string, measuredAt?: string }} [opts]
 * @returns {{ statePath: string, state: object }}
 */
export function recordVolumeState(volumeId, measured, opts = {}) {
  const state = loadVolumesState();
  state.version = STATE_VERSION;
  if (opts.manifestSha256) {
    state.manifest = { sha256: opts.manifestSha256 };
  }
  state.volumes = state.volumes || {};
  state.volumes[volumeId] = {
    // Marks recorded by other live paths (e.g. `syncedAt`, U204) survive a
    // remeasure: measuring never erases state it did not produce.
    ...(state.volumes[volumeId] || {}),
    files: measured.files,
    bytes: measured.bytes,
    missing: measured.missing ?? false,
    measuredAt: opts.measuredAt ?? new Date().toISOString(),
    corpora: (measured.corpora || []).map((c) => ({
      id: c.id,
      path: c.path,
      label: c.label,
      files: c.files,
      bytes: c.bytes,
      missing: c.missing ?? false
    }))
  };
  const statePath = writeVolumesState(state);
  return { statePath, state };
}
